version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "devops-ecr"
    IMAGE_TAG: "latest"
    AWS_DEFAULT_REGION: "ap-south-1"
    REPOSITORY_URI: "123456789012.dkr.ecr.ap-south-1.amazonaws.com/devops-ecr" # <-- your real URI here

phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Build completed on `date`

artifacts:
  files: "**/*"
